"""
Data Validation Module
======================

Central validation framework for all data fetched from the internet,
generated by LLMs, or computed by financial tools.

Ensures reliability by:
- Validating web search results (URL, freshness, credibility)
- Validating LLM JSON responses (schema, ranges, hallucination detection)
- Validating financial calculations (limits, brackets, sanity checks)
- Generating structured validation reports with confidence scores
"""

import json
import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any
from urllib.parse import urlparse

logger = logging.getLogger(__name__)


# ============================================================================
# VALIDATION REPORT
# ============================================================================

@dataclass
class ValidationReport:
    """Structured validation output attached to every agent/tool result."""
    is_valid: bool = True
    confidence_score: float = 1.0
    warnings: list[str] = field(default_factory=list)
    corrections_applied: list[str] = field(default_factory=list)
    sources_verified: list[dict[str, Any]] = field(default_factory=list)
    validation_timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def add_warning(self, warning: str):
        self.warnings.append(warning)
        # Degrade confidence for each warning
        self.confidence_score = max(0.0, self.confidence_score - 0.1)

    def add_correction(self, correction: str):
        self.corrections_applied.append(correction)

    def add_source(self, url: str, credibility: float, domain: str):
        self.sources_verified.append({
            "url": url,
            "credibility_score": credibility,
            "domain": domain,
            "verified_at": datetime.now(timezone.utc).isoformat()
        })

    def to_dict(self) -> dict[str, Any]:
        return {
            "is_valid": self.is_valid,
            "confidence_score": round(self.confidence_score, 2),
            "warnings": self.warnings,
            "corrections_applied": self.corrections_applied,
            "sources_verified": self.sources_verified,
            "validation_timestamp": self.validation_timestamp
        }

    @property
    def status_badge(self) -> str:
        """Return a status badge string for display."""
        if self.confidence_score >= 0.8:
            return "🟢 Verified"
        elif self.confidence_score >= 0.5:
            return "🟡 Partially Verified"
        else:
            return "🔴 Unverified"


# ============================================================================
# INDIA TAX GROUND TRUTH — for cross-checking LLM outputs
# ============================================================================

INDIA_TAX_GROUND_TRUTH = {
    "deduction_limits": {
        "80C": 150000,
        "80D": 150000,
        "80E": None,  # No limit
        "80TTA": 10000,
        "80TTB": 50000,
        "80CCD": 150000,
        "80CCD(1B)": 50000,
        "80DDB": 100000,
        "80G": None,  # No limit (100% or 50%)
        "80U": 75000,
        "80U_severe": 125000,
        "10(13A)": None,  # Calculated
    },
    "standard_deduction": 75000,  # New regime FY 2024-25
    "standard_deduction_old": 50000,
    "cess_rate": 0.04,
    "max_tax_rate": 0.30,
    "rebate_87a_limit": 700000,  # New regime
    "nps_extra_deduction": 50000,  # 80CCD(1B)
}

TRUSTED_DOMAINS = {
    "incometax.gov.in": 1.0,
    "incometaxindia.gov.in": 1.0,
    "cbdt.gov.in": 0.95,
    "cbic.gov.in": 0.95,
    "rbi.org.in": 0.95,
    "sebi.gov.in": 0.90,
    "india.gov.in": 0.90,
    "pib.gov.in": 0.85,
    "economictimes.indiatimes.com": 0.70,
    "livemint.com": 0.65,
    "moneycontrol.com": 0.65,
    "cleartax.in": 0.75,
    "taxguru.in": 0.70,
}


# ============================================================================
# WEB DATA VALIDATOR
# ============================================================================

class WebDataValidator:
    """Validates data fetched from web search APIs (Tavily, etc.)."""

    def __init__(self):
        self.logger = logging.getLogger("validator.web")

    def validate_search_results(
        self,
        results: dict[str, Any],
        query: str
    ) -> tuple[dict[str, Any], ValidationReport]:
        """
        Validate web search results and add credibility metadata.

        Args:
            results: Raw search results from Tavily/fallback
            query: Original search query

        Returns:
            (validated_results, validation_report)
        """
        report = ValidationReport()

        if not results.get("success"):
            report.is_valid = False
            report.confidence_score = 0.0
            report.add_warning("Search request failed")
            return results, report

        search_results = results.get("result", {}).get("results", [])

        if not search_results:
            report.add_warning("No search results returned")
            report.confidence_score = 0.3
            return results, report

        validated_results = []
        for item in search_results:
            validated_item = self._validate_single_result(item, report)
            if validated_item:
                validated_results.append(validated_item)

        # Update results with validated items
        results["result"]["results"] = validated_results
        results["validation"] = report.to_dict()

        # Overall confidence based on source quality
        if validated_results:
            avg_credibility = sum(
                r.get("credibility_score", 0.5) for r in validated_results
            ) / len(validated_results)
            report.confidence_score = min(report.confidence_score, avg_credibility)

        return results, report

    def _validate_single_result(
        self,
        item: dict[str, Any],
        report: ValidationReport
    ) -> dict[str, Any] | None:
        """Validate a single search result item."""
        url = item.get("url", "")
        title = item.get("title", "")
        content = item.get("content", "")

        # URL format validation
        if url:
            try:
                parsed = urlparse(url)
                if not parsed.scheme or not parsed.netloc:
                    report.add_warning(f"Malformed URL skipped: {url[:50]}")
                    return None
                domain = parsed.netloc.lower().replace("www.", "")
            except Exception:
                domain = "unknown"
        else:
            domain = "unknown"

        # Content sanitization — strip dangerous patterns
        if content:
            content = self._sanitize_content(content)

        # Source credibility scoring
        credibility = self._score_credibility(domain)
        report.add_source(url, credibility, domain)

        # Freshness check (if date metadata available)
        date_str = item.get("date", item.get("published_date"))
        freshness_warning = self._check_freshness(date_str)
        if freshness_warning:
            report.add_warning(freshness_warning)

        # Return validated item with metadata
        return {
            **item,
            "content": content,
            "credibility_score": credibility,
            "domain": domain,
            "is_trusted_source": credibility >= 0.8,
            "validated": True
        }

    def _score_credibility(self, domain: str) -> float:
        """Score source credibility based on domain."""
        # Check exact match first
        if domain in TRUSTED_DOMAINS:
            return TRUSTED_DOMAINS[domain]

        # Check subdomain match
        for trusted, score in TRUSTED_DOMAINS.items():
            if domain.endswith(f".{trusted}") or trusted.endswith(f".{domain}"):
                return score * 0.9

        # Government domains get high base credibility
        if domain.endswith(".gov.in") or domain.endswith(".nic.in"):
            return 0.85

        # Default credibility for unknown sources
        return 0.4

    def _sanitize_content(self, content: str) -> str:
        """Sanitize content by removing potentially harmful patterns."""
        # Remove HTML tags
        content = re.sub(r'<[^>]+>', '', content)
        # Remove script injections
        content = re.sub(r'(?i)<script.*?</script>', '', content)
        content = re.sub(r'(?i)javascript:', '', content)
        # Remove excessive whitespace
        content = re.sub(r'\s+', ' ', content).strip()
        # Truncate extremely long content
        if len(content) > 5000:
            content = content[:5000] + "..."
        return content

    def _check_freshness(self, date_str: str | None) -> str | None:
        """Check if the data is fresh enough."""
        if not date_str:
            return None

        try:
            # Try common date formats
            for fmt in ["%Y-%m-%d", "%Y-%m-%dT%H:%M:%S", "%d-%m-%Y", "%Y/%m/%d"]:
                try:
                    date = datetime.strptime(date_str.split("T")[0] if "T" in date_str else date_str, fmt)
                    age_days = (datetime.now(timezone.utc) - date).days
                    if age_days > 365:
                        return f"Source data is {age_days} days old — may be outdated"
                    elif age_days > 180:
                        return f"Source data is {age_days} days old — verify for current FY"
                    return None
                except ValueError:
                    continue
        except Exception:
            pass

        return None


# ============================================================================
# LLM RESPONSE VALIDATOR
# ============================================================================

class LLMResponseValidator:
    """Validates LLM (Groq) responses — JSON parsing, schema, hallucination checks."""

    def __init__(self):
        self.logger = logging.getLogger("validator.llm")

    def parse_json_response(self, raw_response: str) -> tuple[dict | None, ValidationReport]:
        """
        Robustly parse JSON from LLM response with multiple fallback strategies.

        Args:
            raw_response: Raw text from LLM

        Returns:
            (parsed_dict_or_None, validation_report)
        """
        report = ValidationReport()

        if not raw_response or not raw_response.strip():
            report.is_valid = False
            report.confidence_score = 0.0
            report.add_warning("Empty LLM response")
            return None, report

        text = raw_response.strip()

        # Strategy 1: Direct JSON parse
        try:
            parsed = json.loads(text)
            self.logger.debug("JSON parsed directly")
            return parsed, report
        except json.JSONDecodeError:
            pass

        # Strategy 2: Extract from markdown code blocks
        code_block_patterns = [
            r'```json\s*\n?(.*?)\n?\s*```',
            r'```\s*\n?(.*?)\n?\s*```',
        ]
        for pattern in code_block_patterns:
            match = re.search(pattern, text, re.DOTALL)
            if match:
                try:
                    parsed = json.loads(match.group(1).strip())
                    report.add_correction("Extracted JSON from markdown code block")
                    return parsed, report
                except json.JSONDecodeError:
                    continue

        # Strategy 3: Find JSON object boundaries
        try:
            # Find first { and last }
            start = text.index('{')
            end = text.rindex('}') + 1
            candidate = text[start:end]
            parsed = json.loads(candidate)
            report.add_correction("Extracted JSON by finding object boundaries")
            return parsed, report
        except (ValueError, json.JSONDecodeError):
            pass

        # Strategy 4: Find JSON array boundaries
        try:
            start = text.index('[')
            end = text.rindex(']') + 1
            candidate = text[start:end]
            parsed = json.loads(candidate)
            report.add_correction("Extracted JSON array by finding boundaries")
            return {"data": parsed}, report
        except (ValueError, json.JSONDecodeError):
            pass

        # Strategy 5: Fix common JSON issues and retry
        try:
            fixed = text
            # Remove trailing commas before } or ]
            fixed = re.sub(r',\s*([}\]])', r'\1', fixed)
            # Replace single quotes with double quotes
            fixed = re.sub(r"(?<![\\])'", '"', fixed)
            # Try to find JSON within
            start = fixed.index('{')
            end = fixed.rindex('}') + 1
            parsed = json.loads(fixed[start:end])
            report.add_correction("Fixed common JSON formatting issues")
            report.add_warning("LLM response required JSON repair")
            return parsed, report
        except (ValueError, json.JSONDecodeError):
            pass

        # All strategies failed
        report.is_valid = False
        report.confidence_score = 0.0
        report.add_warning("Failed to parse JSON from LLM response after all strategies")
        self.logger.error(f"JSON parse failed. Raw response (first 500 chars): {text[:500]}")
        return None, report

    def validate_income_sources(
        self,
        sources: list[dict[str, Any]]
    ) -> tuple[list[dict[str, Any]], ValidationReport]:
        """Validate extracted income sources."""
        report = ValidationReport()
        validated = []

        for source in sources:
            # Required fields check
            if not source.get("type"):
                report.add_warning("Income source missing 'type' field")
                source["type"] = "Other"
                report.add_correction("Defaulted missing income type to 'Other'")

            # Amount validation
            amount = source.get("amount", 0)
            try:
                amount = float(amount)
            except (TypeError, ValueError):
                report.add_warning(f"Invalid amount '{amount}' for {source.get('type')}")
                amount = 0
                report.add_correction(f"Set invalid amount to 0 for {source.get('type')}")

            if amount < 0:
                report.add_warning(f"Negative income amount: {amount}")
                amount = abs(amount)
                report.add_correction(f"Converted negative amount to positive: {amount}")

            if amount > 1_000_000_000:  # > 100 crore — likely hallucination
                report.add_warning(f"Suspiciously large income: ₹{amount:,.0f} — possible hallucination")
                report.confidence_score = max(0.2, report.confidence_score - 0.3)

            source["amount"] = amount
            validated.append(source)

        return validated, report

    def validate_deductions(
        self,
        deductions: list[dict[str, Any]]
    ) -> tuple[list[dict[str, Any]], ValidationReport]:
        """Validate and enforce deduction limits against ground truth."""
        report = ValidationReport()
        validated = []

        for deduction in deductions:
            # Required fields
            if not deduction.get("category"):
                report.add_warning("Deduction missing 'category' field")
                deduction["category"] = "Uncategorized"

            # AGT-001: amount_known=false is a deliberate "the model was not
            # given a real figure to work from" signal (see the prompt in
            # deduction_hunter.py), not malformed data — leave it as-is
            # rather than logging it alongside genuinely invalid input and
            # coercing it to a misleading 0.
            if deduction.get("amount_known") is False:
                deduction["amount"] = None
                validated.append(deduction)
                continue

            # Amount validation
            amount = deduction.get("amount", 0)
            try:
                amount = float(amount)
            except (TypeError, ValueError):
                report.add_warning(f"Invalid deduction amount for {deduction.get('category')}")
                amount = 0

            if amount < 0:
                amount = abs(amount)
                report.add_correction(f"Converted negative deduction to positive: {amount}")

            # Enforce section limits from ground truth
            scheme_code = deduction.get("scheme_code", "")
            if scheme_code:
                # Normalize scheme code
                code_normalized = scheme_code.upper().replace("SECTION ", "").replace("SEC ", "").strip()
                limit = INDIA_TAX_GROUND_TRUTH["deduction_limits"].get(code_normalized)

                if limit is not None and amount > limit:
                    report.add_warning(
                        f"Section {code_normalized}: ₹{amount:,.0f} exceeds limit of ₹{limit:,.0f}"
                    )
                    report.add_correction(
                        f"Capped Section {code_normalized} deduction from ₹{amount:,.0f} to ₹{limit:,.0f}"
                    )
                    amount = limit

            deduction["amount"] = amount
            validated.append(deduction)

        return validated, report

    def validate_intent_response(
        self,
        response_data: dict[str, Any] | None
    ) -> tuple[dict[str, Any], ValidationReport]:
        """Validate intent detection response from LLM."""
        report = ValidationReport()

        if not response_data:
            report.is_valid = False
            report.confidence_score = 0.0
            report.add_warning("No intent data returned from LLM")
            return {"intent": "GENERAL", "confidence": 0.0, "reasoning": "Parse failure"}, report

        # Validate intent field
        valid_intents = {
            "TAX_DEDUCTION", "TAX_SAVINGS", "INVESTMENT_ADVICE", "PORTFOLIO_ANALYSIS",
            "GOVERNMENT_BENEFITS", "ELIGIBILITY_CHECK", "BUSINESS_EXPENSE",
            "FINANCIAL_PLANNING", "COMPLIANCE_CHECK", "TAX_FILING", "TAX_CALCULATION",
            "CROSS_BORDER_TAX", "PRICE_INTELLIGENCE", "TAX_STRATEGY",
            "WEALTH_PLANNING", "GENERAL"
        }

        intent = response_data.get("intent", "GENERAL").upper()
        if intent not in valid_intents:
            report.add_warning(f"Unknown intent '{intent}' — defaulting to GENERAL")
            report.add_correction(f"Replaced unknown intent '{intent}' with GENERAL")
            response_data["intent"] = "GENERAL"

        # Validate confidence
        confidence = response_data.get("confidence", 0.5)
        try:
            confidence = float(confidence)
            confidence = max(0.0, min(1.0, confidence))
        except (TypeError, ValueError):
            confidence = 0.5
            report.add_correction("Fixed invalid confidence value")
        response_data["confidence"] = confidence

        return response_data, report


# ============================================================================
# FINANCIAL DATA VALIDATOR
# ============================================================================

class FinancialDataValidator:
    """Validates financial calculations and data consistency."""

    def __init__(self):
        self.logger = logging.getLogger("validator.financial")

    def validate_tax_calculation(
        self,
        calculation: dict[str, Any]
    ) -> tuple[dict[str, Any], ValidationReport]:
        """Validate tax calculation results."""
        report = ValidationReport()

        total_income = calculation.get("total_income", 0)
        deductions = calculation.get("deductions", 0)
        taxable_income = calculation.get("taxable_income", 0)
        total_tax = calculation.get("total_tax_liability", 0)

        # Sanity: taxable income can't exceed total income
        if taxable_income > total_income:
            report.add_warning("Taxable income exceeds total income")
            report.add_correction(f"Capped taxable income from ₹{taxable_income:,.0f} to ₹{total_income:,.0f}")
            calculation["taxable_income"] = total_income

        # Sanity: tax can't exceed taxable income
        if total_tax > taxable_income and taxable_income > 0:
            report.add_warning(f"Tax (₹{total_tax:,.0f}) exceeds taxable income (₹{taxable_income:,.0f})")
            report.confidence_score = max(0.3, report.confidence_score - 0.3)

        # Sanity: deductions can't exceed total income
        if deductions > total_income and total_income > 0:
            report.add_warning("Total deductions exceed total income")
            report.confidence_score = max(0.4, report.confidence_score - 0.2)

        # Effective tax rate can't exceed max rate + cess
        if total_income > 0:
            effective_rate = total_tax / total_income
            max_effective = INDIA_TAX_GROUND_TRUTH["max_tax_rate"] * (1 + INDIA_TAX_GROUND_TRUTH["cess_rate"])
            if effective_rate > max_effective + 0.05:  # 5% buffer for surcharge
                report.add_warning(
                    f"Effective tax rate ({effective_rate:.1%}) seems too high — max possible ~{max_effective:.1%}"
                )

        # Negative values check
        for field_name in ["total_income", "taxable_income", "total_tax_liability"]:
            val = calculation.get(field_name, 0)
            if isinstance(val, (int, float)) and val < 0:
                report.add_warning(f"Negative value for {field_name}: {val}")

        return calculation, report

    def validate_savings_estimate(
        self,
        savings: float,
        total_income: float,
        total_deductions: float
    ) -> tuple[float, ValidationReport]:
        """Validate that estimated savings are realistic."""
        report = ValidationReport()

        if total_income <= 0:
            return savings, report

        # Savings can't exceed total income
        if savings > total_income:
            report.add_warning(f"Estimated savings (₹{savings:,.0f}) exceed total income (₹{total_income:,.0f})")
            savings = min(savings, total_income * 0.30)  # Cap at 30% of income
            report.add_correction(f"Capped savings estimate to ₹{savings:,.0f}")

        # Savings from deductions can't exceed the max marginal rate * deductions
        max_savings = total_deductions * (INDIA_TAX_GROUND_TRUTH["max_tax_rate"] + INDIA_TAX_GROUND_TRUTH["cess_rate"])
        if savings > max_savings * 1.2:  # 20% buffer
            report.add_warning(
                f"Savings seem inflated: ₹{savings:,.0f} vs max possible ₹{max_savings:,.0f}"
            )

        return savings, report


# ============================================================================
# UNIFIED VALIDATOR
# ============================================================================

class DataValidator:
    """Unified validator that combines all validation modules."""

    def __init__(self):
        self.web = WebDataValidator()
        self.llm = LLMResponseValidator()
        self.financial = FinancialDataValidator()
        self.logger = logging.getLogger("validator")
        self.logger.info("DataValidator initialized with web, LLM, and financial validators")

    def validate_tool_result(
        self,
        tool_name: str,
        result: dict[str, Any]
    ) -> tuple[dict[str, Any], ValidationReport]:
        """
        Validate a tool's result based on its category.

        Args:
            tool_name: Name of the tool that produced the result
            result: Raw tool result

        Returns:
            (validated_result, validation_report)
        """
        report = ValidationReport()

        if not result.get("success", False):
            report.add_warning(f"Tool '{tool_name}' returned failure")
            report.confidence_score = 0.2
            result["validation"] = report.to_dict()
            return result, report

        # Route to appropriate validator based on tool name
        if tool_name in ("web_search_tavily", "search_latest_tax_rules", "search_government_schemes"):
            result, report = self.web.validate_search_results(result, tool_name)

        elif tool_name in ("calculate_tax_liability",):
            calc_data = result.get("result", {})
            if isinstance(calc_data, dict):
                validated_calc, report = self.financial.validate_tax_calculation(calc_data)
                result["result"] = validated_calc

        elif tool_name in ("calculate_deduction_impact", "estimate_tax_refund"):
            # Basic numeric validation
            calc_data = result.get("result", {})
            if isinstance(calc_data, dict):
                for key, val in calc_data.items():
                    if isinstance(val, (int, float)) and val < 0 and key != "refund":
                        report.add_warning(f"Negative value in {tool_name}: {key}={val}")

        # Attach validation metadata
        result["validated"] = report.is_valid
        result["validation_warnings"] = report.warnings
        result["validation"] = report.to_dict()

        return result, report
