"""Refusing to start on a bad secret — PRD-005.

The hole this closes
--------------------
`config.py` shipped `secret_key` defaulting to
`"your-super-secret-key-change-in-production"`. A deployment that never set the
environment variable signs its JWTs with a constant that is in a public
repository, so anyone can mint a token for any user. The app starts, every test
passes, and the only symptom is that authentication does not work — in the
sense that it works for everybody.

Two decisions, and the second is the one that matters
------------------------------------------------------
**Fail at startup, not at first login.** An app that boots and then 500s on
`/auth/login` looks like a bug in the login endpoint. One that refuses to boot,
naming the environment variable, is diagnosed in ten seconds.

**There is no shared default any more.** In development the key is a fresh
random value PER PROCESS, so there is no published constant to leak and no way
to accidentally deploy one. The cost is that a dev login does not survive a
restart, which is a small price and arguably the correct behaviour anyway.
Production has no default at all: the variable is set or the app does not run.

What counts as bad
-------------------
Not just the shipped placeholder. Anything that looks like a placeholder
(`change`, `example`, `secret`, `test`, `xxxx`), anything too short to resist
offline brute force against an HS256 signature, and anything with so little
variety that it is effectively a word. A 32-character run of "aaaa..." is long
and worthless.

Nothing here ever prints the value
-----------------------------------
Every message names the setting and the reason. `fingerprint()` exists for the
case where an operator needs to confirm two environments hold the SAME secret
without either of them revealing it — a truncated SHA-256, which is
comparable but not reversible.
"""

from __future__ import annotations

import hashlib
import re
import secrets
from dataclasses import dataclass
from typing import Any

MIN_SECRET_LENGTH = 32
MIN_DISTINCT_CHARS = 8

# Substrings that give a placeholder away. Deliberately blunt: a real secret
# generated by `secrets.token_urlsafe` will not contain any of them, so a false
# positive costs one regeneration and a false negative costs the product.
PLACEHOLDER_MARKERS = (
    "change", "changeme", "your-", "example", "placeholder", "dummy",
    "sample", "insecure", "default", "please", "todo", "xxxx", "supersecret",
    "super-secret", "secret-key", "secretkey", "password", "12345",
)

# Settings that must never appear in a log line, an error message or a repr.
SENSITIVE_PATHS = (
    "auth.secret_key",
    "llm.api_key",
    "search.tavily_api_key",
    "search.serper_api_key",
    "qdrant.api_key",
    "telegram.bot_token",
    "email.resend_api_key",
    "s3.access_key_id",
    "s3.secret_access_key",
    "database.url",          # carries a password
    "redis.url",
)


class InsecureConfiguration(Exception):
    """Raised at startup. The app must not serve traffic in this state."""


@dataclass(frozen=True, slots=True)
class Problem:
    setting: str
    reason: str
    fix: str

    def __str__(self) -> str:
        return f"{self.setting}: {self.reason} {self.fix}"


def dev_secret() -> str:
    """A fresh key for this process only.

    Not a constant, deliberately. A default that is the same on every machine
    is a published secret, and the only reason the shipped one survived as long
    as it did is that it worked.
    """
    return secrets.token_urlsafe(48)


def looks_like_a_placeholder(value: str) -> bool:
    lowered = value.lower()
    return any(marker in lowered for marker in PLACEHOLDER_MARKERS)


def check_secret(value: str, *, setting: str) -> list[Problem]:
    """Everything wrong with one secret, not just the first thing."""
    problems: list[Problem] = []
    fix = (
        f"Set {setting.upper().replace('.', '__')} to a value from "
        f"`python -c \"import secrets; print(secrets.token_urlsafe(48))\"`."
    )

    if not value:
        return [Problem(setting, "is empty.", fix)]

    if looks_like_a_placeholder(value):
        problems.append(Problem(
            setting,
            "looks like a placeholder rather than a generated secret. A "
            "default that ships in the repository is a published secret — "
            "anyone can sign a token for any user with it.",
            fix,
        ))

    if len(value) < MIN_SECRET_LENGTH:
        problems.append(Problem(
            setting,
            f"is {len(value)} characters; HS256 signatures are brute-forceable "
            f"offline below {MIN_SECRET_LENGTH}.",
            fix,
        ))

    if len(set(value)) < MIN_DISTINCT_CHARS:
        problems.append(Problem(
            setting,
            f"uses only {len(set(value))} distinct characters. Length without "
            f"variety is not entropy — a 64-character run of one letter is a "
            f"one-character secret.",
            fix,
        ))

    return problems


def _get(settings: Any, path: str) -> Any:
    node = settings
    for part in path.split("."):
        node = getattr(node, part, None)
        if node is None:
            return None
    return node


def audit(settings: Any) -> list[Problem]:
    """Every configuration problem that would matter in production.

    Returns rather than raises so that a development run can log the list and
    carry on, and `enforce` can be the single place that decides a problem is
    fatal.
    """
    problems: list[Problem] = []

    secret = _get(settings, "auth.secret_key") or ""
    problems.extend(check_secret(str(secret), setting="auth.secret_key"))

    if getattr(settings, "debug", False):
        problems.append(Problem(
            "debug",
            "is on. Tracebacks and internal paths reach the client.",
            "Set DEBUG=false.",
        ))

    origins = getattr(settings, "allowed_origins", []) or []
    if "*" in origins:
        problems.append(Problem(
            "allowed_origins",
            "is a wildcard, which defeats the point of having it alongside "
            "credentialed requests.",
            "List the exact front-end origins.",
        ))
    # Loopback is loopback whether it is spelled `localhost`, `127.0.0.1` or
    # `[::1]`. Flagging 127.0.0.1 as an insecure origin is a false positive,
    # and a checker that cries wolf on the developer's own machine gets muted.
    if any(
        str(o).startswith("http://")
        and not any(host in str(o) for host in ("localhost", "127.0.0.1", "[::1]"))
        for o in origins
    ):
        problems.append(Problem(
            "allowed_origins",
            "contains a plaintext http:// origin that is not localhost.",
            "Use https:// for anything that is not local development.",
        ))

    db = str(_get(settings, "database.url") or "")
    if "user:pass@" in db or "localhost" in db:
        problems.append(Problem(
            "database.url",
            "is still the development default.",
            "Point it at the production database.",
        ))

    return problems


def enforce(settings: Any) -> None:
    """Refuse to start when it matters. Call this before serving anything.

    Non-production logs and continues: a developer with `debug` on is not a
    security incident, and a checker that blocks local work gets disabled.
    """
    problems = audit(settings)
    if not problems:
        return

    if not getattr(settings, "is_production", False):
        import logging

        for problem in problems:
            logging.getLogger("security.startup").warning(
                "configuration would fail in production — %s", problem,
            )
        return

    raise InsecureConfiguration(
        "Refusing to start. "
        + f"{len(problems)} configuration problem(s) that would be exploitable "
        + "in production:\n  - "
        + "\n  - ".join(str(p) for p in problems)
    )


# ── never print a secret ────────────────────────────────────────────────────

def fingerprint(value: str) -> str:
    """Comparable, not reversible.

    For the operator who needs to confirm two environments hold the same
    secret without either of them revealing it.
    """
    if not value:
        return "unset"
    return "sha256:" + hashlib.sha256(value.encode()).hexdigest()[:12]


_URL_CREDENTIALS = re.compile(r"(?<=//)[^/\s:@]+:[^/\s@]+(?=@)")


def redact(text: str, settings: Any) -> str:
    """Strip every configured secret out of a string.

    Applied to log lines and to error bodies. Longest first, so a secret that
    contains another one as a prefix does not leave a tail behind.
    """
    values = []
    for path in SENSITIVE_PATHS:
        value = _get(settings, path)
        if value and isinstance(value, str) and len(value) >= 6:
            values.append(value)

    out = text
    for value in sorted(values, key=len, reverse=True):
        out = out.replace(value, "[redacted]")

    # A connection string assembled at runtime will not match any single
    # setting, so credentials inside a URL are stripped by shape as well.
    return _URL_CREDENTIALS.sub("[redacted]", out)


__all__ = [
    "MIN_DISTINCT_CHARS",
    "MIN_SECRET_LENGTH",
    "PLACEHOLDER_MARKERS",
    "SENSITIVE_PATHS",
    "InsecureConfiguration",
    "Problem",
    "audit",
    "check_secret",
    "dev_secret",
    "enforce",
    "fingerprint",
    "looks_like_a_placeholder",
    "redact",
]
