"""Initial schema users sessions financial profiles

Revision ID: 62965466c4ca
Revises: ea72dabb03e5
Create Date: 2026-06-07 14:06:54.011204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62965466c4ca'
down_revision: Union[str, None] = 'ea72dabb03e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
