"""
Tax Optimizer Agent - suggests tax optimization strategies and planning.
Recommends timing, filing approaches, and strategic decisions.
"""

import asyncio
import logging
import time
from datetime import date
from typing import Any

from backend.agents.base_agent import AgentOutput, TaxAgent, confidence_score, derive_confidence
from backend.llm import get_llm
from backend.tools.calculation import current_fy

logger = logging.getLogger(__name__)



class TaxOptimizerAgent(TaxAgent):
    """
    Suggests tax optimization strategies and planning.
    
    Recommends:
    - Income timing optimization
    - Deduction timing optimization
    - Investment strategies for tax efficiency
    - Entity structure recommendations
    - Quarterly planning
    - Filing approach optimization
    
    Example:
        agent = TaxOptimizerAgent()
        result = await agent.execute(
            "What's the best way to minimize my taxes?",
            {"annual_income": 500000, "employment_type": "freelance"}
        )
    """

    def __init__(self):
        super().__init__("tax_optimizer_agent")

    async def execute(
        self,
        user_query: str,
        user_context: dict[str, Any],
        tools: Any = None,
        **kwargs
    ) -> AgentOutput:
        """Generate tax optimization strategies."""
        start_time = time.time()
        logger.info(f"TaxOptimizerAgent: Starting execution for user_id: {user_context.get('user_id')}")

        if tools is not None:
            self.set_tools(tools)

        try:
            # Preprocess query
            processed_query = await self.preprocess(user_query)

            # Get user financial data
            user_financial_data = {}
            if self.tools:
                user_data = await self.call_tool(
                    "get_user_profile",
                    user_id=user_context.get("user_id", "unknown")
                )
                if user_data.get("success"):
                    res_payload = user_data.get("result", {})
                    if res_payload:
                        user_financial_data = res_payload.get("financial_profile", {})

            # Use real data merged with context for LLM analysis
            merged_context = {**user_context, **user_financial_data}

            # Generate strategies using LLM
            logger.info("TaxOptimizerAgent: Requesting strategy recommendations from LLM")
            strategies = await self._generate_strategies(
                processed_query,
                merged_context
            )

            # Execute alert engine to identify additional optimization opportunities
            if self.tools:
                alerts_res = await self.call_tool(
                    "generate_tax_saving_alerts",
                    investments=user_financial_data.get("investments", {}),
                    deductions=user_financial_data.get("deductions", {}),
                    current_taxable_income=float(
                        user_financial_data.get("annual_income", 0) or user_context.get("annual_income", 0)
                    ),
                    age=int(user_context.get("age", 0) or 0),
                )
                if alerts_res.get("success"):
                    alerts = alerts_res.get("result", {}).get("alerts", [])
                    for alert in alerts:
                        # Avoid adding duplicates if already generated by LLM
                        if not any(alert["section"].lower() in str(s.get("scheme_code", "")).lower() for s in strategies):
                            strategies.append({
                                "name": alert["title"],
                                "strategy_name": alert["title"],
                                "scheme_code": alert["section"],
                                "estimated_savings": alert["potential_saving"],
                                "action_required": alert["message"],
                                "action": alert["message"],
                                "description": alert["message"],
                                "priority": alert["severity"].upper()
                            })

            # Check deadlines to suggest timely updates
            upcoming_deadlines = []
            if self.tools:
                deadlines_res = await self.call_tool("check_upcoming_deadlines")
                if deadlines_res.get("success"):
                    upcoming_deadlines = deadlines_res.get("result", {}).get("deadlines", [])

            # For each strategy, verify eligibility and calculate impact.
            # Each strategy's checks (eligibility, then scheme details, then
            # deduction impact) are still sequential — the second and third
            # depend on the first two's results — but strategies are
            # independent OF EACH OTHER, and this used to await them one
            # strategy at a time. With up to eight strategies each making
            # two or three tool round-trips, that sequential sum was the
            # dominant cost in this agent timing out in practice at the
            # orchestrator's 20s default (see api/suggestions.py). Running
            # them concurrently turns that sum into roughly the cost of the
            # single slowest strategy instead.
            annual_income = float(user_financial_data.get("annual_income", 0) or user_context.get("annual_income", 0))

            async def _validate(strategy: dict[str, Any]) -> dict[str, Any] | None:
                is_eligible = True
                if self.tools and strategy.get("scheme_code"):
                    eligibility = await self.call_tool(
                        "check_scheme_eligibility",
                        scheme_code=strategy.get("scheme_code"),
                        user_age=int(user_context.get("age", 35)),
                        user_income=annual_income,
                        has_health_insurance=bool(user_financial_data.get("health_insurance", False)),
                        has_education_loan=bool(user_financial_data.get("education_loan", False))
                    )
                    is_eligible = eligibility.get("success") and eligibility.get("result", {}).get("eligible", True)

                if not is_eligible:
                    return None

                # AGT-001 bugfix. This used to feed `calculate_deduction_impact`
                # (a genuinely deterministic tool — it recomputes tax before/after
                # via backend.core rather than a marginal-rate guess) with
                # `strategy.get("estimated_savings")`: a number the LLM had
                # invented three steps earlier in `_generate_strategies`. A real
                # tool call downstream of a fabricated input is still a
                # fabricated result — it just looks computed. The only honest
                # amount to test is the scheme's actual statutory limit, read
                # from `get_scheme_details`, never from what the model guessed.
                scheme_limit: float | None = None
                if self.tools and strategy.get("scheme_code"):
                    details = await self.call_tool(
                        "get_scheme_details",
                        scheme_code=strategy.get("scheme_code")
                    )
                    if details.get("success"):
                        scheme_details = details.get("result", {}).get("details", {})
                        strategy["details"] = scheme_details
                        limit = scheme_details.get("limit")
                        if isinstance(limit, (int, float)):
                            scheme_limit = float(limit)

                if self.tools and scheme_limit is not None:
                    savings = await self.call_tool(
                        "calculate_deduction_impact",
                        deduction_amount=scheme_limit,
                        current_taxable_income=annual_income
                    )
                    if savings.get("success"):
                        # tax_savings is a decimal STRING (Money.to_json()),
                        # never a JSON number — see benefits_discovery.py's
                        # identical note.
                        strategy["savings"] = float(savings.get("result", {}).get("tax_savings", 0))
                        strategy["savings_basis"] = f"full statutory limit for {strategy.get('scheme_code')}"
                    else:
                        strategy["savings"] = None
                else:
                    # No scheme_code, or the scheme has no fixed statutory
                    # limit to test against (e.g. a home-office deduction,
                    # which scales with actual expenses nobody has stated
                    # yet). Left unset rather than defaulted to 0, which
                    # would read as "no benefit" instead of "not yet known".
                    strategy["savings"] = None

                strategy["eligible"] = True
                return strategy

            validated_results = await asyncio.gather(*(_validate(s) for s in strategies))
            validated_strategies = [s for s in validated_results if s is not None]

            # Sum only strategies with a real, tool-computed figure. A
            # strategy with savings=None contributed nothing here before too
            # (`s.get("savings", 0)` silently treated a missing figure as
            # zero) — now that gap is visible instead of silently averaged in.
            computed_strategies = [s for s in validated_strategies if s.get("savings") is not None]
            uncomputed_strategies = [s for s in validated_strategies if s.get("savings") is None]
            potential_savings = sum(s["savings"] for s in computed_strategies)

            # Create reminders. Two weeks before the real FY-end (31 March,
            # not 31 December) — was hardcoded to "2024-12-15": the wrong
            # month for the Indian tax year AND, by the time this agent was
            # actually wired to any UI, already years in the past.
            if self.tools:
                fy = current_fy()
                fy_end_year = int(fy.split("-")[0]) + 1
                reminder_date = date(fy_end_year, 3, 15).isoformat()
                for strategy in validated_strategies:
                    timeline_str = str(strategy.get("timeline", "")).lower()
                    if "year-end" in timeline_str or "this year" in timeline_str:
                        await self.call_tool(
                            "create_reminder",
                            user_id=user_context.get("user_id", "unknown"),
                            reminder_text=f"Implement: {strategy.get('name', strategy.get('strategy_name', 'Strategy'))}",
                            reminder_date=reminder_date
                        )

            # Postprocess
            result = {
                "strategies": validated_strategies,
                "validated_strategies": validated_strategies,
                "total_estimated_savings": potential_savings,
                "estimated_annual_savings": potential_savings,
                "savings_not_yet_determinable": [
                    s.get("name", s.get("strategy_name", "strategy")) for s in uncomputed_strategies
                ],
                "implementation_timeline": await self._get_timeline(validated_strategies),
                "upcoming_tax_deadlines": upcoming_deadlines,
                "risks_and_considerations": await self._get_considerations(validated_strategies),
                "quarterly_action_items": await self._get_action_items(validated_strategies)
            }

            # Save analysis
            if self.tools:
                await self.call_tool(
                    "save_analysis",
                    user_id=user_context.get("user_id", "unknown"),
                    analysis_type="tax_optimization",
                    analysis_data={"strategies": validated_strategies},
                    agent_name=self.name
                )

            result = await self.postprocess(result)

            execution_time = (time.time() - start_time) * 1000

            logger.info(f"Generated {len(validated_strategies)} validated optimization strategies")

            return self._create_output(
                result=result,
                status="success",
                confidence=confidence_score(derive_confidence()),
                reasoning="Strategies generated with tool-calculated savings",
                execution_time_ms=execution_time
            )

        except Exception as e:
            logger.error(f"Error in tax optimizer: {e}")
            execution_time = (time.time() - start_time) * 1000

            return self._create_output(
                result={"error": str(e)},
                status="error",
                confidence=0.0,  # execution failed — not a score
                reasoning=f"Error: {e!s}",
                execution_time_ms=execution_time
            )


    async def _generate_strategies(
        self,
        user_query: str,
        user_context: dict[str, Any]
    ) -> list[dict[str, Any]]:
        """Use LLM to generate tax optimization strategies."""

        employment_type = user_context.get("employment_type", "individual")
        annual_income = user_context.get("annual_income", 0)

        prompt = f"""Generate personalized tax optimization strategies for this user.

Employment type: {employment_type}
Annual income: ₹{annual_income:,.0f}
User question: "{user_query}"

Suggest specific, actionable tax strategies. For each, provide:
1. Strategy name
2. Description (what to do)
3. Implementation difficulty (Easy/Medium/Hard)
4. Risk level (Low/Medium/High)
5. Timeline (When to implement)
6. Scheme code (e.g. 80C, 80D, 80E, 80TTA, 80TTB, 80CCD, or null if none)

Do NOT estimate a rupee savings figure. That is computed separately from your
description, from the actual statutory limit of the scheme you cite — not
from anything you calculate. Any savings number you include will be discarded.

Respond in JSON format:
{{
  "strategies": [
    {{
      "name": "Section 80C investments",
      "description": "Invest in ELSS, PPF, life insurance to claim 80C deduction",
      "difficulty": "Easy",
      "risk": "Low",
      "timeline": "Before year-end",
      "action": "Open ELSS account and invest up to the 80C limit",
      "scheme_code": "80C"
    }},
    {{
      "name": "Home office deduction",
      "description": "Claim a share of home rent/mortgage as business expense (for self-employed)",
      "difficulty": "Medium",
      "risk": "Low",
      "timeline": "From next tax year",
      "action": "Maintain rent receipts and utility bills",
      "scheme_code": null
    }}
  ]
}}

Important: Only suggest legal, compliant strategies. Respond ONLY with valid JSON."""

        try:
            message = await get_llm().complete(prompt, max_tokens=2000)

            response_text = message.text.strip()
            if "```json" in response_text:
                response_text = response_text.split("```json")[1].split("```")[0].strip()
            elif "```" in response_text:
                response_text = response_text.split("```")[1].split("```")[0].strip()
            import json
            response_data = json.loads(response_text)

            strategies = response_data.get("strategies", [])
            # Belt and braces: the prompt says not to, but nothing stops a
            # model from doing it anyway. Any rupee figure the model attaches
            # is discarded here, unconditionally, before it can reach a user
            # — the real amount is computed later from the scheme's actual
            # statutory limit, never from what the model guessed.
            for strategy in strategies:
                strategy.pop("estimated_savings", None)
                strategy.pop("estimated_amount", None)

            return strategies

        except Exception as e:
            logger.error(f"Error generating strategies: {e}")
            return []

    async def _get_timeline(
        self,
        strategies: list[dict[str, Any]]
    ) -> dict[str, list[str]]:
        """Organize strategies by implementation timeline."""

        timeline = {
            "immediate": [],
            "this_quarter": [],
            "this_year": [],
            "next_year": []
        }

        timeline_mapping = {
            "Now": "immediate",
            "Immediately": "immediate",
            "This quarter": "this_quarter",
            "This month": "this_quarter",
            "Before year-end": "this_year",
            "This year": "this_year",
            "Next year": "next_year",
            "From next tax year": "next_year"
        }

        for strategy in strategies:
            strategy_timeline = strategy.get("timeline", "")

            bucket = "this_year"  # default
            for key, value in timeline_mapping.items():
                if key.lower() in strategy_timeline.lower():
                    bucket = value
                    break

            timeline[bucket].append(
                f"{strategy.get('name')}: {strategy.get('action', '')}"
            )

        return timeline

    async def _get_considerations(
        self,
        strategies: list[dict[str, Any]]
    ) -> list[str]:
        """Get risks and considerations for the recommended strategies."""

        considerations = []

        high_risk = [s for s in strategies if s.get("risk") == "High"]
        if high_risk:
            considerations.append(
                f"⚠ {len(high_risk)} high-risk strategies suggested - consult CA before implementation"
            )

        hard_strategies = [s for s in strategies if s.get("difficulty") == "Hard"]
        if hard_strategies:
            considerations.append(
                "Complex strategies require professional implementation guidance"
            )

        considerations.extend([
            "All recommendations comply with Indian tax laws as of current year",
            "Maintain detailed documentation for all deductions claimed",
            "Consult a qualified Chartered Accountant for personalized advice",
            "Tax laws change annually - review strategies with latest rules"
        ])

        return considerations

    async def _get_action_items(
        self,
        strategies: list[dict[str, Any]]
    ) -> dict[str, list[str]]:
        """Extract quarterly action items from strategies."""

        quarters = {
            "Q1": [],
            "Q2": [],
            "Q3": [],
            "Q4": []
        }

        for strategy in strategies:
            action = strategy.get("action", "")
            timeline = strategy.get("timeline", "")

            if "immediately" in timeline.lower() or "now" in timeline.lower():
                quarters["Q1"].append(action)
            elif "quarter" in timeline.lower():
                quarters["Q2"].append(action)
            elif "year-end" in timeline.lower():
                quarters["Q4"].append(action)
            else:
                quarters["Q2"].append(action)  # default to Q2

        return quarters
