"""
Tax Optimizer Agent - suggests tax optimization strategies and planning.
Recommends timing, filing approaches, and strategic decisions.
"""

import time
import logging
from typing import Dict, Any
from groq import Groq

from backend.agents.base_agent import TaxAgent, AgentOutput
from backend.config import settings

logger = logging.getLogger(__name__)

# Initialize Groq client
client = Groq(api_key=settings.llm.api_key)


class TaxOptimizerAgent(TaxAgent):
    """
    Suggests tax optimization strategies and planning.
    
    Recommends:
    - Income timing optimization
    - Deduction timing optimization
    - Investment strategies for tax efficiency
    - Entity structure recommendations
    - Quarterly planning
    - Filing approach optimization
    
    Example:
        agent = TaxOptimizerAgent()
        result = await agent.execute(
            "What's the best way to minimize my taxes?",
            {"annual_income": 500000, "employment_type": "freelance"}
        )
    """
    
    def __init__(self):
        super().__init__("tax_optimizer_agent")
    
    async def execute(
        self,
        user_query: str,
        user_context: Dict[str, Any],
        tools: Any = None,
        **kwargs
    ) -> AgentOutput:
        """Generate tax optimization strategies."""
        start_time = time.time()
        logger.info(f"TaxOptimizerAgent: Starting execution for user_id: {user_context.get('user_id')}")
        
        if tools is not None:
            self.set_tools(tools)
            
        try:
            # Preprocess query
            processed_query = await self.preprocess(user_query)
            
            # Get user financial data
            user_financial_data = {}
            if self.tools:
                user_data = await self.call_tool(
                    "get_user_profile",
                    user_id=user_context.get("user_id", "unknown")
                )
                if user_data.get("success"):
                    res_payload = user_data.get("result", {})
                    if res_payload:
                        user_financial_data = res_payload.get("financial_profile", {})
            
            # Use real data merged with context for LLM analysis
            merged_context = {**user_context, **user_financial_data}
            
            # Generate strategies using LLM
            logger.info("TaxOptimizerAgent: Requesting strategy recommendations from LLM")
            strategies = await self._generate_strategies(
                processed_query,
                merged_context
            )
            
            # Execute alert engine to identify additional optimization opportunities
            if self.tools:
                alerts_res = await self.call_tool(
                    "generate_tax_saving_alerts",
                    investments=user_financial_data.get("investments", {}),
                    deductions=user_financial_data.get("deductions", {})
                )
                if alerts_res.get("success"):
                    alerts = alerts_res.get("result", {}).get("alerts", [])
                    for alert in alerts:
                        # Avoid adding duplicates if already generated by LLM
                        if not any(alert["section"].lower() in str(s.get("scheme_code", "")).lower() for s in strategies):
                            strategies.append({
                                "name": alert["title"],
                                "strategy_name": alert["title"],
                                "scheme_code": alert["section"],
                                "estimated_savings": alert["potential_saving"],
                                "action_required": alert["message"],
                                "action": alert["message"],
                                "description": alert["message"],
                                "priority": alert["severity"].upper()
                            })

            # Check deadlines to suggest timely updates
            upcoming_deadlines = []
            if self.tools:
                deadlines_res = await self.call_tool("check_upcoming_deadlines")
                if deadlines_res.get("success"):
                    upcoming_deadlines = deadlines_res.get("result", {}).get("deadlines", [])
            
            # For each strategy, verify eligibility and calculate impact
            validated_strategies = []
            for strategy in strategies:
                is_eligible = True
                if self.tools and strategy.get("scheme_code"):
                    # Check if user is eligible
                    eligibility = await self.call_tool(
                        "check_scheme_eligibility",
                        scheme_code=strategy.get("scheme_code"),
                        user_age=int(user_context.get("age", 35)),
                        user_income=float(user_financial_data.get("annual_income", 0) or user_context.get("annual_income", 0)),
                        has_health_insurance=bool(user_financial_data.get("health_insurance", False)),
                        has_education_loan=bool(user_financial_data.get("education_loan", False))
                    )
                    is_eligible = eligibility.get("success") and eligibility.get("result", {}).get("eligible", True)
                
                if is_eligible:
                    # Get scheme details
                    if self.tools and strategy.get("scheme_code"):
                        details = await self.call_tool(
                            "get_scheme_details",
                            scheme_code=strategy.get("scheme_code")
                        )
                        if details.get("success"):
                            strategy["details"] = details.get("result", {}).get("details", {})
                    
                    # Calculate potential savings
                    if self.tools:
                        savings = await self.call_tool(
                            "calculate_deduction_impact",
                            deduction_amount=float(strategy.get("estimated_savings", 0) or strategy.get("estimated_amount", 0)),
                            current_taxable_income=float(user_financial_data.get("annual_income", 0) or user_context.get("annual_income", 0))
                        )
                        if savings.get("success"):
                            strategy["savings"] = savings.get("result", {}).get("tax_savings", 0)
                        else:
                            strategy["savings"] = 0
                    else:
                        strategy["savings"] = 0
                        
                    strategy["eligible"] = True
                    validated_strategies.append(strategy)
            
            # Calculate potential impact from validated strategies
            potential_savings = sum(s.get("savings", 0) for s in validated_strategies)
            
            # Create reminders
            if self.tools:
                for strategy in validated_strategies:
                    timeline_str = str(strategy.get("timeline", "")).lower()
                    if "year-end" in timeline_str or "this year" in timeline_str:
                        await self.call_tool(
                            "create_reminder",
                            user_id=user_context.get("user_id", "unknown"),
                            reminder_text=f"Implement: {strategy.get('name', strategy.get('strategy_name', 'Strategy'))}",
                            reminder_date="2024-12-15"
                        )
            
            # Postprocess
            result = {
                "strategies": validated_strategies,
                "validated_strategies": validated_strategies,
                "total_estimated_savings": potential_savings,
                "estimated_annual_savings": potential_savings,
                "implementation_timeline": await self._get_timeline(validated_strategies),
                "upcoming_tax_deadlines": upcoming_deadlines,
                "risks_and_considerations": await self._get_considerations(validated_strategies),
                "quarterly_action_items": await self._get_action_items(validated_strategies)
            }
            
            # Save analysis
            if self.tools:
                await self.call_tool(
                    "save_analysis",
                    user_id=user_context.get("user_id", "unknown"),
                    analysis_type="tax_optimization",
                    analysis_data={"strategies": validated_strategies},
                    agent_name=self.name
                )
            
            result = await self.postprocess(result)
            
            execution_time = (time.time() - start_time) * 1000
            
            logger.info(f"Generated {len(validated_strategies)} validated optimization strategies")
            
            return self._create_output(
                result=result,
                status="success",
                confidence=0.78,
                reasoning="Strategies generated with tool-calculated savings",
                execution_time_ms=execution_time
            )
        
        except Exception as e:
            logger.error(f"Error in tax optimizer: {e}")
            execution_time = (time.time() - start_time) * 1000
            
            return self._create_output(
                result={"error": str(e)},
                status="error",
                confidence=0.0,
                reasoning=f"Error: {str(e)}",
                execution_time_ms=execution_time
            )
    
    
    async def _generate_strategies(
        self,
        user_query: str,
        user_context: Dict[str, Any]
    ) -> list[Dict[str, Any]]:
        """Use LLM to generate tax optimization strategies."""
        
        employment_type = user_context.get("employment_type", "individual")
        annual_income = user_context.get("annual_income", 0)
        
        prompt = f"""Generate personalized tax optimization strategies for this user.

Employment type: {employment_type}
Annual income: ₹{annual_income:,.0f}
User question: "{user_query}"

Suggest specific, actionable tax strategies. For each, provide:
1. Strategy name
2. Description (what to do)
3. Estimated annual savings (₹)
4. Implementation difficulty (Easy/Medium/Hard)
5. Risk level (Low/Medium/High)
6. Timeline (When to implement)
7. Scheme code (e.g. 80C, 80D, 80E, 80TTA, 80TTB, 80CCD, or null if none)

Respond in JSON format:
{{
  "strategies": [
    {{
      "name": "Section 80C investments",
      "description": "Invest in ELSS, PPF, life insurance to claim 80C deduction (max ₹150,000)",
      "estimated_savings": 30000,
      "difficulty": "Easy",
      "risk": "Low",
      "timeline": "Before year-end",
      "action": "Open ELSS account and invest ₹150,000",
      "scheme_code": "80C"
    }},
    {{
      "name": "Home office deduction",
      "description": "Claim 30% of home rent/mortgage as business expense (for self-employed)",
      "estimated_savings": 60000,
      "difficulty": "Medium",
      "risk": "Low",
      "timeline": "From next tax year",
      "action": "Maintain rent receipts and utility bills",
      "scheme_code": null
    }}
  ]
}}

Important: Only suggest legal, compliant strategies. Respond ONLY with valid JSON."""

        try:
            message = client.chat.completions.create(
                model=settings.llm.model,
                max_tokens=2000,
                messages=[{"role": "user", "content": prompt}]
            )
            
            response_text = message.choices[0].message.content.strip()
            if "```json" in response_text:
                response_text = response_text.split("```json")[1].split("```")[0].strip()
            elif "```" in response_text:
                response_text = response_text.split("```")[1].split("```")[0].strip()
            import json
            response_data = json.loads(response_text)
            
            return response_data.get("strategies", [])
        
        except Exception as e:
            logger.error(f"Error generating strategies: {e}")
            return []
    
    async def _calculate_impact(
        self,
        strategies: list[Dict[str, Any]],
        user_context: Dict[str, Any]
    ) -> float:
        """Calculate total potential tax savings from all strategies."""
        
        total_savings = sum(s.get("estimated_savings", 0) for s in strategies)
        
        # Adjust for risk level
        for strategy in strategies:
            if strategy.get("risk") == "High":
                # Reduce savings estimate by 30% for high-risk strategies
                total_savings -= (strategy.get("estimated_savings", 0) * 0.3)
        
        return max(0, total_savings)
    
    async def _get_timeline(
        self,
        strategies: list[Dict[str, Any]]
    ) -> Dict[str, list[str]]:
        """Organize strategies by implementation timeline."""
        
        timeline = {
            "immediate": [],
            "this_quarter": [],
            "this_year": [],
            "next_year": []
        }
        
        timeline_mapping = {
            "Now": "immediate",
            "Immediately": "immediate",
            "This quarter": "this_quarter",
            "This month": "this_quarter",
            "Before year-end": "this_year",
            "This year": "this_year",
            "Next year": "next_year",
            "From next tax year": "next_year"
        }
        
        for strategy in strategies:
            strategy_timeline = strategy.get("timeline", "")
            
            bucket = "this_year"  # default
            for key, value in timeline_mapping.items():
                if key.lower() in strategy_timeline.lower():
                    bucket = value
                    break
            
            timeline[bucket].append(
                f"{strategy.get('name')}: {strategy.get('action', '')}"
            )
        
        return timeline
    
    async def _get_considerations(
        self,
        strategies: list[Dict[str, Any]]
    ) -> list[str]:
        """Get risks and considerations for the recommended strategies."""
        
        considerations = []
        
        high_risk = [s for s in strategies if s.get("risk") == "High"]
        if high_risk:
            considerations.append(
                f"⚠ {len(high_risk)} high-risk strategies suggested - consult CA before implementation"
            )
        
        hard_strategies = [s for s in strategies if s.get("difficulty") == "Hard"]
        if hard_strategies:
            considerations.append(
                "Complex strategies require professional implementation guidance"
            )
        
        considerations.extend([
            "All recommendations comply with Indian tax laws as of current year",
            "Maintain detailed documentation for all deductions claimed",
            "Consult a qualified Chartered Accountant for personalized advice",
            "Tax laws change annually - review strategies with latest rules"
        ])
        
        return considerations
    
    async def _get_action_items(
        self,
        strategies: list[Dict[str, Any]]
    ) -> Dict[str, list[str]]:
        """Extract quarterly action items from strategies."""
        
        quarters = {
            "Q1": [],
            "Q2": [],
            "Q3": [],
            "Q4": []
        }
        
        for strategy in strategies:
            action = strategy.get("action", "")
            timeline = strategy.get("timeline", "")
            
            if "immediately" in timeline.lower() or "now" in timeline.lower():
                quarters["Q1"].append(action)
            elif "quarter" in timeline.lower():
                quarters["Q2"].append(action)
            elif "year-end" in timeline.lower():
                quarters["Q4"].append(action)
            else:
                quarters["Q2"].append(action)  # default to Q2
        
        return quarters